# Generated by Django 6.1.1 on 2026-09-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_social', models.CharField(blank=True, max_length=200, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anos_letivos', to='core.escola')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=10)),
                ('sala', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.anoletivo')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['serie', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('matricula_funcional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('turmas', models.ManyToManyField(blank=True, related_name='professores', to='core.turma')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('transferida', 'Transferida'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=15)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['aluno__nome_completo'],
            },
        ),
        migrations.AddConstraint(
            model_name='anoletivo',
            constraint=models.UniqueConstraint(fields=('escola', 'ano'), name='ano_unico_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('ano_letivo', 'nome'), name='turma_unica_por_ano'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma'), name='matricula_unica_por_turma'),
        ),
    ]
